FROM node:lts-slim
WORKDIR /root
ADD packages packages
ADD LICENSE-AGPL3.txt LICENSE

# Local
ADD docker/modify.js modify.js
RUN yarn config set registry https://registry.npm.taobao.org/ && \
    node modify.js hydrooj vjudge && \
    rm modify.js

# Hydro
RUN prefix="file:/root/packages" && \
    yarn global add pm2 $prefix/utils $prefix/hydrooj $prefix/ui-default \
    hydro-pdf-preview \
    $prefix/vjudge \
    $prefix/onlyoffice \
    $prefix/sonic && \
    rm -rf packages

# Entrypoint
ENTRYPOINT (test -e /root/.hydro/init.sh && sh /root/.hydro/init.sh); pm2-runtime start hydrooj
