name: Test

on:
  pull_request:
    branches: ["master"]

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn build:ui:production
